#!/bin/bash 
# pre-commit.sh

# TODO: 
# This doesn't work for the first commit which atm must be done with git commit -n 
# Fix this later 
#
#

function safe_exit { 
    git stash pop -q
    exit $1 
}
exec < /dev/tty
ROOT=$(git rev-parse --show-toplevel)

git stash -q --keep-index

# ----------------------------------------------------
# Test

mkdir -p $ROOT/build
cd $ROOT/build

echo "Running CMake" 
cmake ..
if [ $? -ne 0 ]; then 
    echo "Commit aborted because CMake failed"
    safe_exit 1
fi

echo "Running Make"
make -j 8
if [ $? -ne 0 ]; then 
    echo "Commit aborted because Make failed" 
    safe_exit 1
fi
echo "Done with Make"
 

# do some linting 
cd $ROOT
FILES=$(git diff --cached --name-only) 

for file in $FILES; do 
    scripts/lint.sh $file
    if [ $? -ne 0 ]; then 
        safe_exit 1
    fi 
done 

# ----------------------------------------------------

cd $ROOT
safe_exit 0
